# Generated by Django 5.2.7 on 2025-11-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmanager', '0002_alter_clinic_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='paystack_subaccount_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
