# Generated by Django 5.1.1 on 2026-05-21 12:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_payment_reference'),
        ('clinicmanager', '0006_alter_clinic_options_clinic_email_clinic_is_active_and_more'),
        ('patient', '0012_alter_consultation_options_alter_doctor_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at', '-id']},
        ),
        migrations.AddField(
            model_name='bill',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='clinicmanager.clinic'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='patient.consultation'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MPESA', 'M-Pesa'), ('ONLINE', 'Online'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('manual', 'Manual')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['clinic', 'is_paid'], name='billing_bil_clinic__08f985_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['patient', 'is_paid'], name='billing_bil_patient_548eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['created_at'], name='billing_bil_created_94a3b1_idx'),
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['bill'], name='billing_bil_bill_id_227720_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='billing_pay_status_b7739e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bill', 'status'], name='billing_pay_bill_id_a65a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at'], name='billing_pay_paid_at_3dd15c_idx'),
        ),
    ]
