# Generated by Django 5.2.7 on 2025-10-30 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
        ('patient', '0006_consultation_family_planning_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='labresult',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.consultation'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='lab_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.labtest'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
