# Generated by Django 5.2.7 on 2025-10-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0004_lab_labtest_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='category',
            field=models.CharField(choices=[('Test', 'Lab Test'), ('Scan', 'Imaging / Scan')], default='Test', max_length=20),
        ),
    ]
