# Generated by Django 5.2.7 on 2025-10-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0005_labtest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='lab_type',
            field=models.CharField(choices=[('Internal', 'Internal (Performed In-House)'), ('External', 'External (Referral Lab)')], default='Internal', help_text='Select whether this lab performs tests in-house or refers them externally.', max_length=20),
        ),
        migrations.AddField(
            model_name='labtest',
            name='reference_max',
            field=models.CharField(blank=True, help_text='Upper limit of normal range', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='reference_min',
            field=models.CharField(blank=True, help_text='Lower limit of normal range', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='reference_text',
            field=models.CharField(blank=True, help_text='For textual or complex ranges (e.g., Negative, Non-reactive, Normal)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
