# Generated by Django 5.2.7 on 2025-10-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0006_lab_lab_type_labtest_reference_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='category',
            field=models.CharField(choices=[('Test', 'Lab Test'), ('Scan', 'Imaging / Scan')], default='Test', max_length=80),
        ),
    ]
