# Generated by Django 5.2.7 on 2025-10-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0007_alter_labtest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
