# Generated by Django 5.2.7 on 2025-11-03 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmanager', '0002_alter_clinic_created_by'),
        ('emr', '0008_alter_labtest_name'),
        ('patient', '0006_consultation_family_planning_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_queues', to='clinicmanager.clinic')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_queues', to='patient.consultation')),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_queues', to='emr.lab')),
                ('lab_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_queues', to='emr.labtest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_queues', to='patient.patient')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('clinic', 'lab', 'queue_number')},
            },
        ),
    ]
