# Generated by Django 5.2.7 on 2025-12-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0009_labqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
