# Generated by Django 5.1.1 on 2026-05-21 12:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmanager', '0006_alter_clinic_options_clinic_email_clinic_is_active_and_more'),
        ('emr', '0013_alter_labresult_result_value'),
        ('patient', '0012_alter_consultation_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='labresult',
            options={'ordering': ['-result_date']},
        ),
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='lab',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='clinicmanager.clinic'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_type',
            field=models.CharField(choices=[('Internal', 'Internal (Performed In-House)'), ('External', 'External (Referral Lab)')], default='Internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='labqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='labqueue',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], db_index=True, default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patient.consultation'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='lab_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='emr.labtest'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='result_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='category',
            field=models.CharField(choices=[('Test', 'Lab Test'), ('Scan', 'Imaging / Scan')], db_index=True, default='Test', max_length=80),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='emr.lab'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='reference_max',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='reference_min',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='reference_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='lab',
            index=models.Index(fields=['clinic', 'lab_type'], name='emr_lab_clinic__ad587d_idx'),
        ),
        migrations.AddIndex(
            model_name='labqueue',
            index=models.Index(fields=['clinic', 'status'], name='emr_labqueu_clinic__f6eb22_idx'),
        ),
        migrations.AddIndex(
            model_name='labqueue',
            index=models.Index(fields=['lab', 'status'], name='emr_labqueu_lab_id_baa2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='labqueue',
            index=models.Index(fields=['created_at'], name='emr_labqueu_created_4f4b26_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['consultation', 'result_date'], name='emr_labresu_consult_6beb58_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['lab_test'], name='emr_labresu_lab_tes_ca0fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['name'], name='emr_labtest_name_ec2f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['category', 'is_active'], name='emr_labtest_categor_e56c51_idx'),
        ),
    ]
