# Generated by Django 5.1.1 on 2026-05-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_options_chatroom_clinic_and_more'),
        ('clinicmanager', '0006_alter_clinic_options_clinic_email_clinic_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('clinic', 'name')},
        ),
    ]
