# Generated by Django 5.2.7 on 2025-12-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_historicalitem_description_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
