# Generated by Django 5.2.7 on 2025-12-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_historicalitem_price_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
