# Generated by Django 5.1.1 on 2026-05-21 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmanager', '0006_alter_clinic_options_clinic_email_clinic_is_active_and_more'),
        ('inventory', '0006_alter_item_options'),
        ('patient', '0012_alter_consultation_options_alter_doctor_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumptionrecord',
            options={'ordering': ['-used_at']},
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'ordering': ['name'], 'verbose_name': 'Item Category', 'verbose_name_plural': 'Item Categories'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Stock Location', 'verbose_name_plural': 'Stock Locations'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='clinic',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinicmanager.clinic'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinicmanager.clinic'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='clinicmanager.clinic'),
        ),
        migrations.AddField(
            model_name='location',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='clinicmanager.clinic'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='clinicmanager.clinic'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='clinicmanager.clinic'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='from_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumptions', to='inventory.stock'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='used_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalconsumptionrecord',
            name='used_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In (Purchase)'), ('OUT', 'Stock Out (Consumption)'), ('TRANSFER', 'Transfer Between Locations'), ('ADJUST', 'Manual Adjustment')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Ordered'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_lines', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In (Purchase)'), ('OUT', 'Stock Out (Consumption)'), ('TRANSFER', 'Transfer Between Locations'), ('ADJUST', 'Manual Adjustment')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='consumptionrecord',
            index=models.Index(fields=['item', 'used_at'], name='inventory_c_item_id_50063b_idx'),
        ),
        migrations.AddIndex(
            model_name='consumptionrecord',
            index=models.Index(fields=['consultation'], name='inventory_c_consult_60dcfa_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['clinic', 'name'], name='inventory_i_clinic__2f8ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['clinic', 'is_active'], name='inventory_i_clinic__a7087b_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['barcode'], name='inventory_i_barcode_209767_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['clinic', 'name'], name='inventory_l_clinic__9260a1_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['clinic', 'status'], name='inventory_p_clinic__576940_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['item'], name='inventory_s_item_id_3aba05_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['location'], name='inventory_s_locatio_bb95d2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'created_at'], name='inventory_s_item_id_a9fe64_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='inventory_s_movemen_018f99_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['clinic', 'name'], name='inventory_s_clinic__d7b8e0_idx'),
        ),
    ]
