# Generated by Django 5.1.1 on 2026-05-21 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_consumptionrecord_options_and_more'),
        ('patient', '0012_alter_consultation_options_alter_doctor_options_and_more'),
        ('prescription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-prescribed_at']},
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patient.consultation'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dispensed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['consultation'], name='prescriptio_consult_3854ae_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['dispensed'], name='prescriptio_dispens_186c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['item'], name='prescriptio_item_id_00298d_idx'),
        ),
    ]
