# Generated by Django 5.1.1 on 2026-05-21 12:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_bill_options_alter_payment_options_and_more'),
        ('clinicmanager', '0006_alter_clinic_options_clinic_email_clinic_is_active_and_more'),
        ('patient', '0012_alter_consultation_options_alter_doctor_options_and_more'),
        ('specialists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtcase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='debtfollowup',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='equipmentitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='externallabrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='homevisit',
            options={'ordering': ['-visit_date']},
        ),
        migrations.AlterModelOptions(
            name='notificationforspecialist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='nursingnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='servicecatalog',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sonographystudy',
            options={'ordering': ['-performed_at']},
        ),
        migrations.AlterModelOptions(
            name='specialisttask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='supplyinvoice',
            options={'ordering': ['-invoice_date']},
        ),
        migrations.AlterField(
            model_name='debtcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='debtcase',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('promised', 'Promised to Pay'), ('paid', 'Paid'), ('written_off', 'Written Off')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='debtfollowup',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('call', 'Phone Call'), ('sms', 'SMS'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='debtfollowup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='externallabrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='externallabrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to External Lab'), ('received', 'Results Received'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='externallabresult',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_lab_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homevisit',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='homevisit',
            name='visit_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='notificationforspecialist',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_notifications', to='clinicmanager.clinic'),
        ),
        migrations.AlterField(
            model_name='notificationforspecialist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notificationforspecialist',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationforspecialist',
            name='seen',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='nursingnote',
            name='category',
            field=models.CharField(choices=[('observation', 'Observation'), ('iv', 'IV / Fluids'), ('acute', 'Acute Management'), ('suturing', 'Suturing'), ('other', 'Other')], db_index=True, default='observation', max_length=30),
        ),
        migrations.AlterField(
            model_name='nursingnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='role',
            field=models.CharField(choices=[('sonographer', 'Sonographer'), ('nurse', 'Nurse / Observation'), ('cardiologist', 'Cardiologist'), ('radiologist', 'Radiologist'), ('physician', 'Physician'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='sonographystudy',
            name='performed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sonographystudy',
            name='study_type',
            field=models.CharField(choices=[('ultrasound', 'Ultrasound'), ('doppler', 'Doppler')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='role',
            field=models.CharField(choices=[('sonographer', 'Sonographer'), ('nurse', 'Nurse / Observation'), ('cardiologist', 'Cardiologist'), ('radiologist', 'Radiologist'), ('physician', 'Physician'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='specialisttask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='specialisttask',
            name='role',
            field=models.CharField(choices=[('sonographer', 'Sonographer'), ('nurse', 'Nurse / Observation'), ('cardiologist', 'Cardiologist'), ('radiologist', 'Radiologist'), ('physician', 'Physician'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='specialisttask',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='specialists.servicecatalog'),
        ),
        migrations.AlterField(
            model_name='specialisttask',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplyinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplyinvoice',
            name='invoice_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supplyinvoice',
            name='vendor',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='debtcase',
            index=models.Index(fields=['clinic', 'status'], name='specialists_clinic__7507b6_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentitem',
            index=models.Index(fields=['clinic', 'name'], name='specialists_clinic__a7f88a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationforspecialist',
            index=models.Index(fields=['recipient', 'seen'], name='specialists_recipie_6a2950_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecatalog',
            index=models.Index(fields=['clinic', 'role', 'is_active'], name='specialists_clinic__161e69_idx'),
        ),
        migrations.AddIndex(
            model_name='specialistprofile',
            index=models.Index(fields=['clinic', 'role'], name='specialists_clinic__afcdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='specialistprofile',
            index=models.Index(fields=['clinic', 'is_active'], name='specialists_clinic__b5e6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='specialisttask',
            index=models.Index(fields=['clinic', 'status'], name='specialists_clinic__a40f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='specialisttask',
            index=models.Index(fields=['clinic', 'role', 'status'], name='specialists_clinic__3d365a_idx'),
        ),
        migrations.AddIndex(
            model_name='specialisttask',
            index=models.Index(fields=['assigned_to', 'status'], name='specialists_assigne_ce2606_idx'),
        ),
    ]
