# Generated by Django 5.2.7 on 2025-11-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vapid_private_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vapid_public_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
