# Generated by Django 5.2.7 on 2025-10-27 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='clinicmanager.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clinicmanager.clinic')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patient.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chief_complaints', models.TextField(blank=True, null=True)),
                ('history_of_presenting_illness', models.TextField(blank=True, null=True)),
                ('past_medical_history', models.TextField(blank=True, null=True)),
                ('past_surgical_history', models.TextField(blank=True, null=True)),
                ('drug_allergies', models.TextField(blank=True, null=True)),
                ('current_medication', models.TextField(blank=True, null=True)),
                ('comorbid_factors', models.TextField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('spo2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('respiration_rate', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('general_examination', models.TextField(blank=True, null=True)),
                ('heent', models.CharField(blank=True, max_length=100, null=True)),
                ('cvs', models.CharField(blank=True, max_length=100, null=True)),
                ('pa', models.CharField(blank=True, max_length=100, null=True)),
                ('mss', models.CharField(blank=True, max_length=100, null=True)),
                ('rr', models.CharField(blank=True, max_length=100, null=True)),
                ('cms', models.CharField(blank=True, max_length=100, null=True)),
                ('imaging', models.CharField(blank=True, choices=[('ultrasound', 'Ultrasound'), ('chest_xray', 'Chest X-ray'), ('mri', 'MRI'), ('ctscan', 'CT Scan'), ('colonoscopy', 'Colonoscopy'), ('endoscopy', 'Endoscopy'), ('barium_meal', 'Barium Meal'), ('none', 'None')], max_length=50, null=True)),
                ('laboratory', models.CharField(blank=True, choices=[('blood_test', 'Blood Test'), ('swab_test', 'Swab Test'), ('sputum_test', 'Sputum Test'), ('urine_test', 'Urine Test'), ('stool_test', 'Stool Test'), ('high_vaginal_swab', 'High Vaginal Swab Test'), ('spermatozoa_test', 'Spermatozoa Test'), ('ophthalmology_test', 'Ophthalmology Test'), ('none', 'None')], max_length=50, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('management', models.CharField(blank=True, choices=[('supportive', 'Supportive'), ('preventive', 'Preventive'), ('counseling', 'Counseling'), ('referral', 'Referral')], max_length=50, null=True)),
                ('medication', models.TextField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patient.patient')),
            ],
        ),
    ]
