# Generated by Django 5.2.7 on 2025-10-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='cvs',
            new_name='cns',
        ),
    ]
