# Generated by Django 5.2.7 on 2025-10-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_rename_cvs_consultation_cns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='cms',
            new_name='cvs',
        ),
        migrations.AddField(
            model_name='consultation',
            name='image_findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lab_findings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
