# Generated by Django 5.2.7 on 2025-10-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='family_planning_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='sexual_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='vaccination_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
