# Generated by Django 5.2.7 on 2025-11-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_queue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('inlab', 'In Lab'), ('fromLab', 'From Lab')], default='waiting', max_length=20),
        ),
    ]
