# Generated by Django 5.2.7 on 2025-12-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_queue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='labor_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
