# Generated by Django 5.2.7 on 2025-12-12 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_consultation_labor_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
