# Generated by Django 5.1.1 on 2026-01-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_alter_consultation_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together=set(),
        ),
    ]
