# Generated by Django 5.1.1 on 2026-05-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_consultation_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='priority',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], db_index=True, default='normal', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('inlab', 'In Lab'), ('fromLab', 'From Lab')], db_index=True, default='waiting', max_length=20, null=True),
        ),
    ]
