# Generated by Django 5.1.1 on 2026-05-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_alter_queue_priority_alter_queue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
    ]
