"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import logging.handlers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w327xjg37#0_ju6^&y38i6qz_7=k&shku$oxq=xu8etsp)78%$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '194.60.201.69',
    'medwema.com',
    'www.medwema.com',
    'localhost',
    '127.0.0.1',
    '50a2923067d8.ngrok-free.app'
]


CSRF_TRUSTED_ORIGINS = [
    'http://medwema.com',
    'https://medwema.com',
    'http://www.medwema.com',
    'https://www.medwema.com',
    'http://localhost',
    'http://127.0.0.1',
    'https://50a2923067d8.ngrok-free.app'
]
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'patient',
    'django_bootstrap5',
    'crispy_forms',
    'crispy_bootstrap5',
    'authentication',
    "widget_tweaks",
    'clinicmanager',
    'emr',
    'home',
    'django_select2',
    'inventory',
    'rest_framework',
    'django_filters',
    'simple_history',
    'billing',
    'prescription',
    'channels',
    'webpush',
    'notification',
    'chat',
    'specialists',
    'drf_spectacular',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

JAZZMIN_SETTINGS = {
    "site_title": "Medwema Admin",
    "site_header": "Medwema EMR",
    "site_brand": "Medwema",
    "site_logo": None,
    "login_logo": None,
    "welcome_sign": "Welcome to Medwema EMR — Healthcare Management System",
    "copyright": "Lunyamwi Technologies",
    "search_model": ["authentication.User", "patient.Patient"],
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
        {"name": "API Docs", "url": "/api/docs/", "new_window": True},
    ],
    "usermenu_links": [
        {"name": "My Profile", "url": "/profile/"},
        {"model": "authentication.user"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "authentication": "fas fa-users-cog",
        "authentication.User": "fas fa-user",
        "patient": "fas fa-procedures",
        "patient.Patient": "fas fa-user-injured",
        "patient.Doctor": "fas fa-user-md",
        "patient.Consultation": "fas fa-notes-medical",
        "patient.Queue": "fas fa-list-ol",
        "billing": "fas fa-file-invoice-dollar",
        "billing.Bill": "fas fa-file-invoice",
        "billing.Payment": "fas fa-credit-card",
        "billing.PaystackSubaccount": "fas fa-university",
        "emr": "fas fa-flask",
        "emr.Lab": "fas fa-building",
        "emr.LabTest": "fas fa-vials",
        "emr.LabResult": "fas fa-clipboard-list",
        "emr.LabQueue": "fas fa-stream",
        "inventory": "fas fa-boxes",
        "inventory.Item": "fas fa-box",
        "inventory.Stock": "fas fa-warehouse",
        "inventory.StockMovement": "fas fa-exchange-alt",
        "inventory.PurchaseOrder": "fas fa-shopping-cart",
        "inventory.Supplier": "fas fa-truck",
        "inventory.Location": "fas fa-map-marker-alt",
        "inventory.ItemCategory": "fas fa-tags",
        "inventory.ConsumptionRecord": "fas fa-minus-circle",
        "prescription": "fas fa-pills",
        "prescription.Prescription": "fas fa-prescription-bottle-alt",
        "specialists": "fas fa-stethoscope",
        "specialists.SpecialistTask": "fas fa-tasks",
        "specialists.SonographyStudy": "fas fa-wave-square",
        "specialists.NursingNote": "fas fa-heartbeat",
        "specialists.HomeVisit": "fas fa-home",
        "specialists.DebtCase": "fas fa-exclamation-triangle",
        "specialists.EquipmentItem": "fas fa-tools",
        "home": "fas fa-globe",
        "home.BlogPost": "fas fa-blog",
        "home.BlogCategory": "fas fa-folder",
        "home.Subscriber": "fas fa-envelope",
        "clinicmanager": "fas fa-hospital",
        "clinicmanager.Clinic": "fas fa-hospital-alt",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Medwema EMR API",
    "DESCRIPTION": (
        "REST API for the Medwema Electronic Medical Records system. "
        "All endpoints require authentication. Data is automatically scoped to the "
        "authenticated user's clinic — cross-clinic data access is not possible."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayRequestDuration": True,
    },
    "COMPONENT_SPLIT_REQUEST": True,
}

WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": os.getenv("VAPID_PUBLIC_KEY").strip(),
    "VAPID_PRIVATE_KEY": os.getenv("VAPID_PRIVATE_KEY").strip(),
    "VAPID_ADMIN_EMAIL": os.getenv("VAPID_ADMIN_EMAIL").strip(),
}

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

ACCOUNT_SIGNUP_FORM_CLASS = 'authentication.forms.CustomSignupForm'

AUTH_USER_MODEL = 'authentication.User'

CRISPY_TEMPLATE_PACK = "bootstrap5"

ASGI_APPLICATION = 'setup.asgi.application'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]
MIDDLEWARE += ['simple_history.middleware.HistoryRequestMiddleware']


ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DBNAME').strip(),
        'USER': os.environ.get('POSTGRES_USERNAME').strip(),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD').strip(),
        'HOST': os.environ.get('POSTGRES_HOST').strip(),
        'PORT': os.environ.get('POSTGRES_PORT').strip(),
    }
}

LOGIN_REDIRECT_URL = '/patients/'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = '/usr/src/app/static'
MEDIA_URL = "/media/"
MEDIA_ROOT ='/usr/src/app/media'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_USER').strip()
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASSWORD').strip()

SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 1 week
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


# Paystack config
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY').strip()  # set in env or setting.strip()s
PAYSTACK_BASE_URL = 'https://api.paystack.co'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": BASE_DIR / ".django_cache",
        "TIMEOUT": 86400,
    }
}

SELECT2_CACHE_BACKEND = "default"
X_FRAME_OPTIONS = "SAMEORIGIN"

# ─── Logging ──────────────────────────────────────────────────────────────────

LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{levelname}] {name}: {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "[{levelname}] {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "level": "DEBUG",
        },
        "app_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOGS_DIR / "medwema.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
            "level": "DEBUG",
        },
        "error_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOGS_DIR / "errors.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
            "level": "ERROR",
        },
    },
    "loggers": {
        "patient":      {"handlers": ["console", "app_file", "error_file"], "level": "DEBUG", "propagate": False},
        "emr":          {"handlers": ["console", "app_file", "error_file"], "level": "DEBUG", "propagate": False},
        "billing":      {"handlers": ["console", "app_file", "error_file"], "level": "DEBUG", "propagate": False},
        "inventory":    {"handlers": ["console", "app_file", "error_file"], "level": "DEBUG", "propagate": False},
        "prescription": {"handlers": ["console", "app_file", "error_file"], "level": "DEBUG", "propagate": False},
        "specialists":  {"handlers": ["console", "app_file", "error_file"], "level": "DEBUG", "propagate": False},
        "notification": {"handlers": ["console", "app_file", "error_file"], "level": "DEBUG", "propagate": False},
        "chat":         {"handlers": ["console", "app_file", "error_file"], "level": "DEBUG", "propagate": False},
        "django":       {"handlers": ["console", "error_file"], "level": "WARNING", "propagate": False},
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
}
